nombresMonstruo = {
    "Gran Jagras": "GJAGR",
    "Great Jagras": "GJAGR",
    "Kulu Ya Ku": "KULUY",
    "Pukei Pukei": "PUKEI",
    "Barroth": "BARRO",
    "Jyuratodus": "JYURA",
    "Tobi Kadachi": "TOBIK",
    "Anjanath": "ANJAN",
    "Rathian": "RATHI",
    "Tzitzi Ya Ku": "TZITZ",
    "Paolumu": "PAOLU",
    "Gran Girros": "GGIRR",
    "Great Girros": "GGIRR",
    "Radobaan": "RADOB",
    "Legiana": "LEGIA",
    "Odogaron": "ODOGA",
    "Rathalos": "RATHA",
    "Diablos": "DIABL",
    "Kirin": "KIRIN",
    "Zorah Magdaros": "ZORAH",
    "Dodogama": "DODOG",
    "Bazelgeuse": "BAZEL",
    "Deviljho": "DEVIL",
    "Pepinillo": "DEVIL",
    "Pickle": "DEVIL",
    "Lavasioth": "LAVAS",
    "Uragaan": "URAGA",
    "Nergigante": "NERGI",
    "Teostra": "TEOST",
    "Lunastra": "LUNAS",
    "Kushala Daora": "DAORA",
    "Vaal Hazak": "HAZAA",
    "Kulve Taroth": "KULVE",
    "Xeno jiiva": "XENOJ",
    "Beotodus": "BEOTO",
    "Banbaro": "BANBA",
    "Barioth": "BARIO",
    "Nargacuga": "NARGA",
    "Naruga Kuruga": "NARGA",
    "Glavenus": "GLAVE",
    "Tigrex": "TIGRE",
    "Brachydios": "BRACH",
    "Velkhana": "VELKH",
    "Namielle": "NAMIE",
    "Shara Ishvalda": "SHARA",
    "Zinogre": "ZINOG",
    "Jinouga": "ZINOG",
    "Yian Garuga": "YIANG",
    "Safi jiiva": "SAFIJ",
    "Rajang": "RAJAN",
    "Alatreon": "ALATR",
    "Begimo": "BEGIM",
    "Behemoth": "BEGIM",
    "Leshen": "LESHE",
    "Rathian Rosa": "RATHI ROS",
    "Pink Rathian": "RATHI ROS",
    "Rathalos Celeste": "RATHA CEL",
    "Azure Rathalos": "RATHA CEL",
    "Rathian Dorada": "RATHI DOR",
    "Gold Rathian": "RATHI DOR",
    "Rathalos Plateado": "RATHA PLA",
    "Silver Rathalos": "RATHA PLA",
    "Diablos Negra": "DIABL NEG",
    "Black Diablos": "DIABL NEG",
    "Tobi Kadachi Vipero": "TOBIK VIP",
    "Viper Tobi Kadachi": "TOBIK VIP",
    "Paolumu Somnus": "PAOLU SOM",
    "Nightshade Paolumu": "PAOLO SOM",
    "Pukei Pukei Coralino": "PUKEI COR",
    "Coral Pukei Pukei": "PUKEI COR",
    "Legiana Aullador": "LEGIA AUL",
    "Shrieking Legiana": "LEGIA AUL",
    "Anjanath Fulgureo": "ANJAN FUL",
    "Fulgur Anjanath": "ANJAN FUL",
    "Glavenus Acidico": "GLAVE ACI",
    "Acidic Glavenus": "GLAVE ACI",
    "Odogaron Ebano": "ODOGA EBA",
    "Ebony Odogaron": "ODOGA EBA",
    "Bazelgeuse Magma": "BAZEL MAG",
    "Seething Bazelgeuse": "BAZEL MAG",
    "Vaal Hazak Esporeo": "HAZAA ESP",
    "Blackveil Vaal Hazak": "HAZAA ESP",
    "Deviljho Salvaje": "DEVIL SAL",
    "Pepinillo Salvaje": "DEVIL SAL",
    "Savage Deviljho": "DEVIL SAL",
    "Savage Pickle": "DEVIL SAL",
    "Nergigante Regio": "NERGI REG",
    "Ruiner Nergigante": "NERGI REG",
    "Yian Garuga Naevus": "YIANG NAE",
    "Scarred Yian Garuga": "YIANG NAE",
    "Tigrex Pardo": "TIGRE PAR",
    "Brute Tigrex": "TIGRE PAR",
    "Zinogre Estigio": "ZINOG EST",
    "Jinouga Estigio": "ZINOG EST",
    "Stygian Zinogre": "ZINOG EST",
    "Stygian Jinouga": "ZINOG EST",
    "Rajang Rabioso": "RAJAN RAB",
    "Furious Rajang": "RAJAN RAB",
    "Brachydios Colerico": "BRACH COL",
    "Raging Brachydios": "BRACH COL",
    "Barioth Cynodon": "BARIO CYN",
    "Frostfang Barioth": "BARIO CYN",
    "Leshen Antiguo": "LESHE ANT",
    "Ancient Leshen": "LESHE ANT",
}
